//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDelete_Gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SDelete_Gui.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot configure.  Check your permissions..
        /// </summary>
        public static string CheckPermissions {
            get {
                return ResourceManager.GetString("CheckPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured. SDelete will use {0} passes.
        /// </summary>
        public static string ConfiguredXPasses {
            get {
                return ResourceManager.GetString("ConfiguredXPasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed unconfiguring.
        /// </summary>
        public static string FailedUnconfiguring {
            get {
                return ResourceManager.GetString("FailedUnconfiguring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many passes will it use?.
        /// </summary>
        public static string HowManyPasses {
            get {
                return ResourceManager.GetString("HowManyPasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to go to Github source code.
        /// </summary>
        public static string InfoToolTip {
            get {
                return ResourceManager.GetString("InfoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to start.
        /// </summary>
        public static string ReadyToStart {
            get {
                return ResourceManager.GetString("ReadyToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDelete.exe not found in {0} and cannot be downloaded from the Internet..
        /// </summary>
        public static string SDeleteNotFoundAndNotDownloadable {
            get {
                return ResourceManager.GetString("SDeleteNotFoundAndNotDownloadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Delete.
        /// </summary>
        public static string SecureDelete {
            get {
                return ResourceManager.GetString("SecureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unconfigured.
        /// </summary>
        public static string Unconfigured {
            get {
                return ResourceManager.GetString("Unconfigured", resourceCulture);
            }
        }
    }
}
